accessLogsFile = "/dev/stdout"
defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  #[entryPoints.web]
  address = ":80"
    [entryPoints.http.redirect]
    regex = "^http://(.*)"
    replacement = "https://$1"
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]


[file]

  [backends]

    [backends.fake]
      [backends.fake.servers.s1]
        url="http://1.2.3.4"

[acme]
email = "long25nt@gmail.com"
caServer = "https://acme-v02.api.letsencrypt.org/directory"
storageFile = "/etc/traefik/acme/acme.json"
#storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
#onDemand = true
OnHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"

[[acme.domains]]
  main = "tocchien360.vn"

[web]
address = ":8080"
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "localhost"
watch = true
swarmmode = true
exposedbydefault = false

