kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql
spec:
  storageClassName: ""  # Static provisioning
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
