kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql
spec:
  storageClassName: "standard"  # Static provisioning
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
